default_language_version:
  python: python3.10

repos:
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    - id: black

  - repo: https://github.com/pycqa/flake8
    rev: 4.0.1
    hooks:
    - id: flake8
      additional_dependencies:
      - "flake8-builtins"
      - "flake8-implicit-str-concat"
      - "flake8-no-pep420"

  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
    - id: isort

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: debug-statements
    - id: check-ast
    - id: check-json
    - id: check-toml
    - id: check-yaml
    - id: detect-private-key

  - repo: https://github.com/stratasan/hadolint-pre-commit
    rev: cdefcb096e520a6daa9552b1d4636f5f1e1729cd
    hooks:
    - id: hadolint
