[tool.coverage.run]
branch = true
dynamic_context = "test_function"
omit = [
  ".direnv/*",
  ".venv/*",
  "*/migrations/*",
  "interactive/asgi.py",
  "interactive/settings.py",
  "interactive/wsgi.py",
  "services/sentry.py",
  "manage.py",
  "reports/*/analysis/*",
]
source = [
  "interactive",
  "reports",
  "services",
  "tests",
]

[tool.coverage.report]
fail_under = 100
show_missing = true
skip_covered = true

[tool.coverage.html]
show_contexts = true

[tool.isort]
profile = "black"
lines_after_imports = 2
skip_glob = [".direnv", "venv", ".venv"]
known_third_party = ["debug_toolbar", "django", "environs", "furl", "lxml", "pytest", "sentry_sdk", "structlog"]

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "interactive.settings"
env = [
  "SECRET_KEY=12345",
]
addopts = "--tb=native --ignore=node_modules --no-migrations"
filterwarnings = [
    "ignore:distutils Version classes are deprecated:DeprecationWarning:pytest_freezegun",
    "ignore:distutils Version classes are deprecated:DeprecationWarning:pytest_responses",
]
markers = [
    "integration: marks tests as slow (deselect with '-m \"not integration\"')",
]
