[tool.black]
exclude = '''
(
  /(
      \.git         # exclude a few common directories
    | \.direnv
    | \.github
    | \.pytest_cache
    | \.venv
    | htmlcov
    | venv
  )/
)
'''

[tool.coverage.run]
branch = true
omit = [
  ".venv/*",
  "*/migrations/*",
  "interactive/asgi.py",
  "interactive/settings.py",
  "interactive/wsgi.py",
  "manage.py",
]

[tool.coverage.report]
fail_under = 100
skip_covered = true

[tool.coverage.html]

[tool.isort]
profile = "black"
lines_after_imports = 2
skip_glob = [".direnv", "venv", ".venv"]

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "interactive.settings"
env = [
  "SECRET_KEY=12345",
]
addopts = "--tb=native --ignore=node_modules --no-migrations"
