# Generated by Django 4.0.4 on 2022-05-04 15:05

import django.db.models.deletion
import timeflake.extensions.django
from django.db import migrations, models

import interactive.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "id",
                    timeflake.extensions.django.TimeflakePrimaryKeyBinary(
                        serialize=False
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "email",
                    models.EmailField(
                        error_messages={
                            "unique": "A user with this email address already exists."
                        },
                        max_length=100,
                        unique=True,
                        verbose_name="email address",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            managers=[
                ("objects", interactive.models.CustomUserManager()),
            ],
        ),
        migrations.CreateModel(
            name="RegistrationRequest",
            fields=[
                (
                    "id",
                    timeflake.extensions.django.TimeflakePrimaryKeyBinary(
                        serialize=False
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=100, verbose_name="Full name"),
                ),
                ("email", models.CharField(max_length=100, verbose_name="Email")),
                (
                    "organisation",
                    models.CharField(max_length=100, verbose_name="Organisation"),
                ),
                (
                    "job_title",
                    models.CharField(max_length=100, verbose_name="Job title"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AnalysisRequest",
            fields=[
                (
                    "id",
                    timeflake.extensions.django.TimeflakePrimaryKeyBinary(
                        serialize=False
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=100, verbose_name="Analysis title"),
                ),
                ("codelist", models.CharField(max_length=255, verbose_name="Codelist")),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="interactive.User",
                    ),
                ),
            ],
        ),
    ]
