# Generated by Django 4.0.4 on 2022-04-22 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interactive", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysisrequest",
            name="codelist",
            field=models.CharField(default="Missing", max_length=255),
            preserve_default=False,
        ),
    ]
