# Generated by Django 4.0.4 on 2022-04-26 10:16

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ("interactive", "0003_alter_analysisrequest_codelist_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysisrequest",
            name="end_date",
            field=models.DateField(
                default=datetime.datetime(2022, 4, 26, 10, 16, 51, 91902, tzinfo=utc)
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="analysisrequest",
            name="start_date",
            field=models.DateField(
                default=datetime.datetime(2022, 4, 26, 10, 16, 59, 800702, tzinfo=utc)
            ),
            preserve_default=False,
        ),
    ]
