# Generated by Django 4.0.4 on 2022-05-18 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("interactive", "0003_alter_analysisrequest_commit_sha"),
    ]

    operations = [
        migrations.RenameField(
            model_name="analysisrequest",
            old_name="codelist",
            new_name="codelist_slug",
        ),
    ]
