# Generated by Django 4.0.4 on 2022-04-26 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("interactive", "0004_analysisrequest_end_date_analysisrequest_start_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysisrequest",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
