# Generated by Django 4.0.4 on 2022-05-18 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interactive", "0004_rename_codelist_analysisrequest_codelist_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysisrequest",
            name="codelist_name",
            field=models.CharField(
                default="unknown", max_length=255, verbose_name="Codelist"
            ),
            preserve_default=False,
        ),
    ]
