# Generated by Django 4.0.4 on 2022-04-27 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interactive", "0005_analysisrequest_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegisterInterest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(max_length=100, verbose_name="Full name"),
                ),
                ("email", models.CharField(max_length=100, verbose_name="Email")),
                (
                    "organisation",
                    models.CharField(max_length=100, verbose_name="Organisation"),
                ),
                (
                    "job_title",
                    models.CharField(max_length=100, verbose_name="Job title"),
                ),
            ],
        ),
    ]
