# Generated by Django 4.0.5 on 2022-06-10 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interactive", "0005_analysisrequest_codelist_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysisrequest",
            name="complete_email_sent_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
