# Generated by Django 4.0.4 on 2022-04-28 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("interactive", "0006_registerinterest"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="RegisterInterest",
            new_name="RegistrationRequest",
        ),
    ]
