# Generated by Django 4.0.5 on 2022-06-10 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interactive", "0006_analysisrequest_done_email_sent"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysisrequest",
            name="job_request_url",
            field=models.TextField(default=""),
        ),
    ]
