# Generated by Django 4.0.5 on 2022-06-13 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interactive", "0006_analysisrequest_done_email_sent"),
    ]

    operations = [
        migrations.AddField(
            model_name="registrationrequest",
            name="approved_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="registrationrequest",
            name="is_approved",
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
