# Generated by Django 4.0.5 on 2022-06-13 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("interactive", "0007_registrationrequest_approved_at_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="registrationrequest",
            old_name="approved_at",
            new_name="processed_at",
        ),
    ]
