# Generated by Django 4.0.5 on 2022-06-15 14:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interactive", "0007_add_analysisrequest_job_request_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="registrationrequest",
            name="review_status",
            field=models.TextField(
                blank=True,
                choices=[("Approved", "Approved"), ("Denied", "Denied")],
                default=None,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="registrationrequest",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name="registrationrequest",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
