# Generated by Django 4.0.4 on 2022-05-04 08:43

import timeflake
import timeflake.extensions.django
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("interactive", "0007_rename_registerinterest_registrationrequest"),
    ]

    operations = [
        migrations.AddField(
            model_name="analysisrequest",
            name="uuid",
            field=timeflake.extensions.django.TimeflakeBinary(default=timeflake.random),
        ),
        migrations.AddField(
            model_name="registrationrequest",
            name="uuid",
            field=timeflake.extensions.django.TimeflakeBinary(default=timeflake.random),
        ),
    ]
