# Generated by Django 4.0.4 on 2022-05-03 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("interactive", "0008_user"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_staff",
        ),
        migrations.RemoveField(
            model_name="user",
            name="is_superuser",
        ),
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
    ]
