# Generated by Django 4.0.4 on 2022-05-04 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("interactive", "0009_remove_analysisrequest_id_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="analysisrequest",
            old_name="uuid",
            new_name="id",
        ),
        migrations.RenameField(
            model_name="registrationrequest",
            old_name="uuid",
            new_name="id",
        ),
    ]
