# Generated by Django 4.0.6 on 2022-07-29 13:15

import timeflake.extensions.django
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("interactive", "0010_add_created_at_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analysisrequest",
            name="id",
            field=timeflake.extensions.django.TimeflakePrimaryKeyBinary(
                error_messages={"invalid": "Invalid timeflake id"}, serialize=False
            ),
        ),
    ]
