# Generated by Django 4.1.4 on 2022-12-14 14:11

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interactive", "0011_alter_analysisrequest_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analysisrequest",
            name="complete_email_sent_at",
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="analysisrequest",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name="registrationrequest",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name="registrationrequest",
            name="review_status",
            field=models.TextField(
                choices=[("Approved", "Approved"), ("Denied", "Denied")],
                default=None,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="registrationrequest",
            name="reviewed_at",
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="registrationrequest",
            name="reviewed_by",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="job_title",
            field=models.CharField(
                default="", max_length=100, verbose_name="Job title"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="organisation",
            field=models.CharField(
                default="", max_length=100, verbose_name="Organisation"
            ),
        ),
    ]
