# Generated by Django 4.1.4 on 2022-12-14 14:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interactive", "0013_drop_default_equals_none_kwarg"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analysisrequest",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="registrationrequest",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="user",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
