# Generated by Django 4.1.4 on 2022-12-15 12:21

import timeflake.extensions.django
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("interactive", "0015_update_is_staff_help_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="registrationrequest",
            name="id",
            field=timeflake.extensions.django.TimeflakePrimaryKeyBinary(
                error_messages={"invalid": "Invalid timeflake id"}, serialize=False
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="id",
            field=timeflake.extensions.django.TimeflakePrimaryKeyBinary(
                error_messages={"invalid": "Invalid timeflake id"}, serialize=False
            ),
        ),
    ]
