# Generated by Django 4.1.4 on 2022-12-14 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("interactive", "0017_switch_char_fields_to_text_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="analysisrequest",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="analysis_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="registrationrequest",
            name="reviewed_by",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reviewed_registration_requests",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
