# Generated by Django 4.1.4 on 2022-12-14 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("interactive", "0018_add_related_names"),
    ]

    operations = [
        migrations.RenameField(
            model_name="analysisrequest",
            old_name="user",
            new_name="created_by",
        ),
    ]
