# Generated by Django 4.1.4 on 2022-12-16 08:54
from django.db import migrations
from django.utils.text import slugify


def add_orgs_and_memberships(apps, schema_editor):
    Org = apps.get_model("interactive", "Org")
    OrgMembership = apps.get_model("interactive", "OrgMembership")
    User = apps.get_model("interactive", "User")

    users_with_orgs = User.objects.exclude(organisation="")

    # create the orgs
    org_names = set(users_with_orgs.values_list("organisation", flat=True))
    Org.objects.bulk_create([Org(name=name, slug=slugify(name)) for name in org_names])

    # assign users to them
    for user in users_with_orgs:
        org = Org.objects.get(name=user.organisation)
        OrgMembership.objects.create(user=user, org=org)


def remove_memberships_and_orgs(apps, schema_editor):
    Org = apps.get_model("interactive", "Org")
    OrgMembership = apps.get_model("interactive", "OrgMembership")

    OrgMembership.objects.all().delete()
    Org.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("interactive", "0020_add_org_and_org_membership"),
    ]

    operations = [
        migrations.RunPython(
            add_orgs_and_memberships,
            reverse_code=remove_memberships_and_orgs,
        )
    ]
