---
name: CI

on:
  push:

jobs:
  assets:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: "npm"

      - name: Install node_modules
        run: npm ci

      - name: Build assets
        run: npm run build

      - name: Store assets
        uses: actions/upload-artifact@v2
        with:
          name: node-assets
          path: assets/dist/bundle

  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: "actions/setup-python@v2"
        with:
          python-version: "3.10"
          cache: "pip"
          cache-dependency-path: requirements.*.txt
      - uses: extractions/setup-just@v1
      - name: Check formatting, linting and import sorting
        run: just check

  test:
    needs: [assets, check]
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: pass
          POSTGRES_DB: interactive
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v2
      - uses: "actions/setup-python@v2"
        with:
          python-version: "3.10"
          cache: "pip"
          cache-dependency-path: requirements.*.txt
      - uses: extractions/setup-just@v1

      - name: Retrieve assets
        uses: actions/download-artifact@v2
        with:
          name: node-assets
          path: assets/dist/bundle

      - name: Run tests
        env:
          SECRET_KEY: 12345 # Fake key for GitHub Actions
        run: |
          just test

  lint-dockerfile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: hadolint/hadolint-action@v1.5.0
        with:
          failure-threshold: error
